<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

     <xacro:include filename="/home/robot/dev_ws/src/agni_2/description/inertial_macros.xacro"/>


    <xacro:property name="body_length" value="0.3"/>
    <xacro:property name="body_width" value="0.3"/>
    <xacro:property name="body_height" value="0.3"/>
    <xacro:property name="body_mass" value="5"/>
    <xacro:property name="wheel_radius" value="0.0415"/>
    <xacro:property name="wheel_thickness" value="0.035"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.02"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.02"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    



  <material name="white">
      <color rgba="1 1 1 1"/>
  </material>

  <material name="orange">
      <color rgba="1 0.3 0.1 1"/>
  </material>

  <material name="blue">
      <color rgba="0.2 0.2 1 1"/>
  </material>

  <material name="black">
      <color rgba="0 0 0 1"/>
  </material>

  <material name="red">
      <color rgba="1 0 0 1"/>
  </material>

<!--/////////////////////////// base link //////////////////////// -->
  <link name="base_link">
     <pose>0 0 0 0 0 -3.14159</pose>
  </link>


<!--/////////////////////////// base footprint link //////////////////////// -->
 <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
  </joint>

  <link name="base_footprint">
  </link>
 
<!--/////////////////////////// body link //////////////////////// -->

      <joint name="body_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}" rpy="0 0 0"/>
    </joint>

    <link name="body">
        <visual>
            <origin xyz="${body_length/2} 0 ${body_height/2}"/>
            <pose xyz="${body_length/2} 0 ${body_height/2}" rz="180.0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${body_length/2} 0 ${body_height/2}"/>
            <pose xyz="${body_length/2} 0 ${body_height/2}" rz="180.0"/>
            <geometry>
                <box size="${body_length} ${body_width} ${body_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${body_length}" y="${body_width}" z="${body_height}">
            <origin xyz="${body_length/2} 0 ${body_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="body">
        <material>Gazebo/Blue</material>
    </gazebo>

<!--/////////////////////////// left wheel link //////////////////////// -->
<joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="${-pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>


 <!--/////////////////////////// right wheel link //////////////////////// -->
  <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

  <!--/////////////////////////// caster wheel link //////////////////////// -->
 <joint name="caster_wheel_joint" type="fixed">
        <parent link="body"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>